#!/usr/bin/env php
<?php

use Pine\Config\Config;
use Pine\Console\InitCommand;
use Pine\Console\NewCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Yaml\Yaml;

define('VERSION', '2.3.4');
define('CONFIG_PATH', $_SERVER[ 'HOME' ] . DIRECTORY_SEPARATOR . "pine.yaml");

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

/**
 * Create our console application
 */
$application = new Application('pine - A CLI installer for Timber', VERSION);

$config = new Config(new Yaml());

/**
 * Add a command to our application
 */
$application->add(new NewCommand($config));
$application->add(new InitCommand($config));

/**
 * Run the application
 */
$application->run();
