#!/usr/bin/env php
<?php

define('VERSION', '2.2.1');

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

/**
 * Create our console application
 */
$application = new \Symfony\Component\Console\Application('pine - A CLI installer for timber', VERSION);

/**
 * Add a command to our application
 */
$application->add(new \Azi\Console\NewCommand());

/**
 * Run the application
 */
$application->run();
