#!/usr/bin/env php
<?php

define('VERSION', '1.0.2');

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

/**
 * Create our console application
 */
$application = new \Symfony\Component\Console\Application('Timber Installer', VERSION);

/**
 * Add a command to our application
 */
$application->add(new \Azi\Console\NewCommand());

/**
 * Run the application
 */
$application->run();